version: "3.8"
services:
    cdnmsredis:
        container_name: cdnmsredis
        command: redis-server --requirepass blahpikachublahpotato
        image: redislabs/rejson:1.0.4
        networks:
            - cdnms
        ports:
            - 6381:6381
    cdnmsserver:
        container_name: cdnmsserver
        depends_on:
            - cdnmsredis
            - cdnmscertbot
        build: ./src
        command: python3 -u /cdnms/main.py
        environment:
            PORT: "${CDNMSPORT}"
            HOSTSERVER: "${HOSTSERVER}"
            REDISPWD: blahpikachublahpotatoq
            TLSCERT: "/etc/letsencrypt/live/${HOSTSERVER}/fullchain.pem"
            TLSKEY: "/etc/letsencrypt/live/${HOSTSERVER}/privkey.pem"
        ports:
            - "${CDNMSPORT}:${CDNMSPORT}"
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
    cdnmscertbot:
        container_name: certbot
        command: certonly --standalone --email sentientoranges@gmail.com --agree-tos --keep --no-eff-email -d ${HOSTSERVER}
        image: certbot/certbot
        networks:
            - cdnms
        ports:
            - 8085:8085
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
networks:
    cdnms:
volumes:
    certbot-etc:
    certbot-var:
